name: my_ci_cd
on:
  workflow_dispatch:

env:
  SOURCE     : "./"
  TARGET     : "~/docker_bind9"
  DOCKER_TAG : "${{ secrets.DOCKERHUB_USERNAME }}/bind9:beta"

jobs:
  # deploy_to_ssh:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: -------Start-CD-----------
  #       run: echo "Start CD message"

  #     - name: GitHub clone code
  #       uses: actions/checkout@v3

  #     - name: Deploy to Server
  #       uses: easingthemes/ssh-deploy@main
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
  #         ARGS           : "-rlgoDzvc -i --delete"
  #         SOURCE         : ${{ env.SOURCE }}
  #         REMOTE_HOST    : ${{ secrets.REMOTE_HOST }}
  #         REMOTE_USER    : ${{ secrets.REMOTE_USER }}
  #         TARGET         : ${{ env.TARGET }}
  #         SCRIPT_BEFORE: |
  #           cd ${{ env.TARGET }}
  #           ls -la
  #         SCRIPT_AFTER: |
  #           cd ${{ env.TARGET }}
  #           ls -la

  #     - name: -------Finish-CD-----------
  #       run: |
  #         echo "🍏 This job's status is ${{ job.status }}."

  build_and_push_docker:
    runs-on: ubuntu-latest

    steps:     
      - name: -------Start-Docker-Build-&-Push-----------
        run: echo "Start Docker-Build-&-Push message"

      - name: GitHub clone code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_TAG }}

      - name: -------FINISH-Docker-Build-&-Push----------
        run: |
          echo "🍏 This job's status is ${{ job.status }}."