name: docker_build

on:
  workflow_dispatch: # Срабатывает при запуске вручную из интерфейса GitHub Actions
# on:
#   push:
#     branches:
#       - main # Срабатывает при коммите в ветку main

env:
  SOURCE     : "./"
  TARGET     : "~/docker_bind9"
  DOCKER_TAG : "${{ secrets.DOCKERHUB_USERNAME }}/bind9:latest"

jobs:
  test_build_bind9:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub clone code
      uses: actions/checkout@v3 # Клонирует репозиторий, на котором запущен деплоймент
      
    - name: Install Bind9
      run: |
        sudo apt-get update
        sudo apt-get install -y bind9
      
    - name: Check Bind9 config
      run: |
        ls -la
        sudo named-checkconf DOCKER/named.conf.local; echo $?
        sudo named-checkconf DOCKER/named.conf.options; echo $?
        # sudo named-checkzone forward.my.zone DOCKER/forward.my.zone; echo $?
        # sudo named-checkzone reverse.my.zone DOCKER/reverse.my.zone; echo $?

    # - name: Start Bind9 service
    #   run: |
    #     sudo systemctl start bind9

  build_docker:
    runs-on: ubuntu-latest
    needs: [test_build_bind9]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: DOCKER/
          file: DOCKER/Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAG }}
  
      - name: -------FINISH-Docker-Build-&-Push----------
        run: |
          echo "🍏 This job's status is ${{ job      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: arturakh/bind9
          readme-filepath: ./README.md.status }}."

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: arturakh/bind9
          readme-filepath: ./README.md